import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FlipNavWrapper from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import UserButton from '@/components/user-button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
        <div className="header-container">
              <FlipNavWrapper />
              <div className="px-5">
              <UserButton />
              </div>
        </div>
        <div> {children}</div>
      </ThemeProvider>
        </body>
      
    </html>
  )
}
