import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FlipNavWrapper from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import UserButton from '@/components/user-button'
import { SessionProvider } from "next-auth/react"
import { auth } from "auth"
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: { children: React.ReactNode}) {
  const session = await auth()
  if (session?.user) {
    session.user = {
      id: session.user.id,
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    }
  }
  return (
    <SessionProvider session={session}> 
    <html lang="en">
      
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
        <div className="header-container">
              <FlipNavWrapper />
              <div className="px-5">
              <UserButton />
              </div>
        </div>
        <div> {children}</div>
      </ThemeProvider>
      <Toaster />
        </body>
      
    </html>
    </SessionProvider>
  )
}
